Repository Romi904/Lemon_Juice, pull requests merged in 2022-10, with the labels that each got.

#1 Create Contributor.md
  Contributor.md
Labels: ACCEPTED, hacktoberfest_accepted

#2 Create tree.c
  tree.c
Labels: good first issue, ACCEPTED, hacktoberfest_accepted

#3 Honeycomb_design.html
  Honeycomb_design.html
Labels: good first issue, ACCEPTED, hacktoberfest_accepted, GREAT WORK, HACKTOBERFEST ACCEPTED

#4 pmp1
  pumpellona.html
Labels: good first issue, ACCEPTED, hacktoberfest_accepted, GREAT WORK, HACKTOBERFEST ACCEPTED

#7 Add files via upload
  hangman_game/idetniftthe_word.py
  hangman_game/words.py
Labels: ACCEPTED

#9 Create sad.html
  sad.html
Labels: hacktoberfest-accepted

#11 Create Kashmir.html
  Kashmir.html
Labels: hacktoberfest-accepted
